### ISSUE TITLE
无法连接到数据库

### ISSUE THREAD

**Issue by axty666** [eolinker/eoapi-remote-server#3]
```
[Nest] 512317  - 07/23/2022, 7:57:41 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (9)...
QueryFailedError: Table 'api_data' already exists
    at QueryFailedError.TypeORMError [as constructor] ($path/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError ($path/src/error/QueryFailedError.ts:9:9)
    at Query.onResult ($path/src/driver/mysql/MysqlQueryRunner.ts:196:37)
    at Query.execute ($path/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket ($path/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket ($path/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart ($path/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> ($path/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
[Nest] 512317  - 07/23/2022, 7:57:41 PM   ERROR [ExceptionHandler] Table 'api_data' already exists
QueryFailedError: Table 'api_data' already exists
    at QueryFailedError.TypeORMError [as constructor] ($path/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError ($path/src/error/QueryFailedError.ts:9:9)
    at Query.onResult ($path/src/driver/mysql/MysqlQueryRunner.ts:196:37)
    at Query.execute ($path/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket ($path/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket ($path/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart ($path/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> ($path/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
```
yarn 与 npm 均试过，数据库尝试过删除 重建对应的数据库 已经确认不是账户密码数据库名填错
$path是文件夹名字 对应的是package.json所在的目录

**Comment by axty666** [comment]
```
import { ConnectionOptions } from 'typeorm';

export default {
  type: 'mysql',
  host: '127.0.0.1',
  port: 3306,
  username: 'root',
  password: '123456',
  database: 'eoapi',
  synchronize: true,
  logging: false,
  entities: ['dist/entities/**/*.js'],
  migrations: ['dist/migrations/**/*.js'],
  migrationsRun: true,
  cli: {
    migrationsDir: 'src/migrations',
  },
} as ConnectionOptions;
```

**Comment by scarqin** [comment]
@axty666 猜测是环境问题，我们最新版已经使用 docker 安装了，请按照步骤试试。
如果还有问题，@buqiyuan 小缘及时跟进

**Comment by axty666** [comment]
> @axty666 猜测是环境问题，我们最新版已经使用 docker 安装了，请按照步骤试试。 如果还有问题，@buqiyuan 小缘及时跟进

使用docker部署后：
```
eoapi-remote-server_1  | [Nest] 27  - 07/23/2022, 9:27:00 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...
eoapi-remote-server_1  | Error: Access denied for user 'root'@'172.25.0.3' (using password: YES)
eoapi-remote-server_1  |     at Packet.asError (/eoapi-remote-server/node_modules/mysql2/lib/packets/packet.js:728:17)
eoapi-remote-server_1  |     at ClientHandshake.execute (/eoapi-remote-server/node_modules/mysql2/lib/commands/command.js:29:26)
eoapi-remote-server_1  |     at PoolConnection.handlePacket (/eoapi-remote-server/node_modules/mysql2/lib/connection.js:456:32)
eoapi-remote-server_1  |     at PacketParser.onPacket (/eoapi-remote-server/node_modules/mysql2/lib/connection.js:85:12)
eoapi-remote-server_1  |     at PacketParser.executeStart (/eoapi-remote-server/node_modules/mysql2/lib/packet_parser.js:75:16)
eoapi-remote-server_1  |     at Socket.<anonymous> (/eoapi-remote-server/node_modules/mysql2/lib/connection.js:92:25)
eoapi-remote-server_1  |     at Socket.emit (node:events:527:28)
eoapi-remote-server_1  |     at addChunk (node:internal/streams/readable:315:12)
eoapi-remote-server_1  |     at readableAddChunk (node:internal/streams/readable:289:9)
eoapi-remote-server_1  |     at Socket.Readable.push (node:internal/streams/readable:228:10)
eoapi-remote-server_1  | [Nest] 20  - 07/23/2022, 9:27:00 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...
eoapi-remote-server_1  | Error: Access denied for user 'root'@'172.25.0.3' (using password: YES)
eoapi-remote-server_1  |     at Packet.asError (/eoapi-remote-server/node_modules/mysql2/lib/packets/packet.js:728:17)
eoapi-remote-server_1  |     at ClientHandshake.execute (/eoapi-remote-server/node_modules/mysql2/lib/commands/command.js:29:26)
eoapi-remote-server_1  |     at PoolConnection.handlePacket (/eoapi-remote-server/node_modules/mysql2/lib/connection.js:456:32)
eoapi-remote-server_1  |     at PacketParser.onPacket (/eoapi-remote-server/node_modules/mysql2/lib/connection.js:85:12)
eoapi-remote-server_1  |     at PacketParser.executeStart (/eoapi-remote-server/node_modules/mysql2/lib/packet_parser.js:75:16)
eoapi-remote-server_1  |     at Socket.<anonymous> (/eoapi-remote-server/node_modules/mysql2/lib/connection.js:92:25)
eoapi-remote-server_1  |     at Socket.emit (node:events:527:28)
eoapi-remote-server_1  |     at addChunk (node:internal/streams/readable:315:12)
eoapi-remote-server_1  |     at readableAddChunk (node:internal/streams/readable:289:9)
eoapi-remote-server_1  |     at Socket.Readable.push (node:internal/streams/readable:228:10)
```
其中的root@ip字段中的ip每一次都不一样

**Comment by buqiyuan** [comment]
> 

你好，尝试将数据库字符集设置为`utf8mb4_general_ci`试试

**Comment by buqiyuan** [comment]
> 

🤔首次使用`docker-compose up -d`启动就有这个问题了吗？

**Comment by axty666** [comment]
![image](https://user-images.githubusercontent.com/76648930/180607681-6fcdb9cb-1124-4e7f-a701-538de0eb6e33.png)


> > 
> 
> 你好，尝试将数据库字符集设置为`utf8mb4_general_ci`试试

**Comment by axty666** [comment]
> > 
> 
> thinking首次使用`docker-compose up -d`启动就有这个问题了吗？

第一次的时候成功运行 但是客户端无法连接到
于是删除重新部署 然后再次使用``docker-compose up -d``启动的时候就是这样了
`docker-compose.yaml`里面的`MYSQL_PASSWORD`和`MYSQL_ROOT_PASSWORD`部分第一次的时候甚至没有改为真实的密码就成功运行没有报错 再次的时候即使改为真实的密码也会报错

**Comment by buqiyuan** [comment]
🤔啊这样，尝试将项目根目录下的`sample`文件夹删了重试呢

**Comment by axty666** [comment]
> thinking啊这样，尝试将项目根目录下的`sample`文件夹和之前产生的容器删掉删了重试呢
sample文件夹和Dockerfile文件吗？

**Comment by axty666** [comment]
> > thinking啊这样，尝试将项目根目录下的`sample`文件夹和之前产生的容器删掉删了重试呢
> 
> sample文件夹和Dockerfile文件吗？

```
eoapi-remote-server_1  | [Nest] 139  - 07/23/2022, 9:57:00 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (7)...
eoapi-remote-server_1  | Error: Access denied for user 'root'@'172.27.0.3' (using password: YES)
eoapi-remote-server_1  |     at Packet.asError (/eoapi-remote-server/node_modules/mysql2/lib/packets/packet.js:728:17)
eoapi-remote-server_1  |     at ClientHandshake.execute (/eoapi-remote-server/node_modules/mysql2/lib/commands/command.js:29:26)
eoapi-remote-server_1  |     at PoolConnection.handlePacket (/eoapi-remote-server/node_modules/mysql2/lib/connection.js:456:32)
eoapi-remote-server_1  |     at PacketParser.onPacket (/eoapi-remote-server/node_modules/mysql2/lib/connection.js:85:12)
eoapi-remote-server_1  |     at PacketParser.executeStart (/eoapi-remote-server/node_modules/mysql2/lib/packet_parser.js:75:16)
eoapi-remote-server_1  |     at Socket.<anonymous> (/eoapi-remote-server/node_modules/mysql2/lib/connection.js:92:25)
eoapi-remote-server_1  |     at Socket.emit (node:events:527:28)
eoapi-remote-server_1  |     at addChunk (node:internal/streams/readable:315:12)
eoapi-remote-server_1  |     at readableAddChunk (node:internal/streams/readable:289:9)
eoapi-remote-server_1  |     at Socket.Readable.push (node:internal/streams/readable:228:10)
eoapi-remote-server_1  | [Nest] 151  - 07/23/2022, 9:57:01 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (7)...
eoapi-remote-server_1  | Error: Access denied for user 'root'@'172.27.0.3' (using password: YES)
eoapi-remote-server_1  |     at Packet.asError (/eoapi-remote-server/node_modules/mysql2/lib/packets/packet.js:728:17)
eoapi-remote-server_1  |     at ClientHandshake.execute (/eoapi-remote-server/node_modules/mysql2/lib/commands/command.js:29:26)
eoapi-remote-server_1  |     at PoolConnection.handlePacket (/eoapi-remote-server/node_modules/mysql2/lib/connection.js:456:32)
eoapi-remote-server_1  |     at PacketParser.onPacket (/eoapi-remote-server/node_modules/mysql2/lib/connection.js:85:12)
eoapi-remote-server_1  |     at PacketParser.executeStart (/eoapi-remote-server/node_modules/mysql2/lib/packet_parser.js:75:16)
eoapi-remote-server_1  |     at Socket.<anonymous> (/eoapi-remote-server/node_modules/mysql2/lib/connection.js:92:25)
eoapi-remote-server_1  |     at Socket.emit (node:events:527:28)
eoapi-remote-server_1  |     at addChunk (node:internal/streams/readable:315:12)
eoapi-remote-server_1  |     at readableAddChunk (node:internal/streams/readable:289:9)
eoapi-remote-server_1  |     at Socket.Readable.push (node:internal/streams/readable:228:10)
^CERROR: Aborting.
```

**Comment by buqiyuan** [comment]
`Dockerfile`不要删，删掉`sample`,如果你安装了`docker desktop`的话，直接删掉如下图所示的`container`和`image`:
<img width="1581" alt="image" src="https://user-images.githubusercontent.com/39730999/180608432-f7e26edd-7423-4d33-b9c7-b81f1c0cf5e2.png">
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/39730999/180608451-fed8c1c9-480d-4b99-a117-1699a29945d8.png">

**Comment by buqiyuan** [comment]
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/39730999/180608542-a8b49ac8-f78a-4283-9f8a-22397f03b000.png">
这里是通过`network`连接服务的，按理说不会有这个问题才对

**Comment by buqiyuan** [comment]
你这里连接不上数据库，主要应该是密码不对，看下这两个地方密码一样吗？
<img width="1619" alt="image" src="https://user-images.githubusercontent.com/39730999/180608677-8cde85c8-4bb6-4c7a-aadc-cfcd7c3f8fda.png">

**Comment by scarqin** [comment]
root'@'172.27.0.3 这个是数据库地址，对外隐藏的，localhost 是服务地址（Node），外部可以访问的

**Comment by axty666** [comment]
> root'@'172.27.0.3 这个是数据库地址，对外隐藏的，localhost 是服务地址（Node），外部可以访问的

原来如此

**Comment by axty666** [comment]
> 你这里连接不上数据库，主要应该是密码不对，看下这两个地方密码一样吗？ <img alt="image" width="1619" src="https://user-images.githubusercontent.com/39730999/180608677-8cde85c8-4bb6-4c7a-aadc-cfcd7c3f8fda.png">

改为一样的后重启 仍然连接不上
![KSDZ{GJTZQPOUFM`7CI(B43](https://user-images.githubusercontent.com/76648930/180609100-cee84e92-44de-4665-bfdc-dcf4283b71d5.png)
```
eoapi-mysql            | 2022-07-23 22:14:45+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.29-1.el8 started.
eoapi-mysql            | 2022-07-23 22:14:45+08:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
eoapi-mysql            | 2022-07-23 22:14:45+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.29-1.el8 started.
eoapi-mysql            | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
eoapi-mysql            | 2022-07-23T14:14:45.719829Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.29) starting as process 1
eoapi-mysql            | 2022-07-23T14:14:45.731273Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
eoapi-mysql            | 2022-07-23T14:14:46.059322Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
eoapi-mysql            | 2022-07-23T14:14:46.298155Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
eoapi-mysql            | 2022-07-23T14:14:46.298306Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
eoapi-mysql            | 2022-07-23T14:14:46.300010Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
eoapi-mysql            | 2022-07-23T14:14:46.328561Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
eoapi-mysql            | 2022-07-23T14:14:46.328761Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.29'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
eoapi-remote-server_1  | [Nest] 20  - 07/23/2022, 10:14:54 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
eoapi-remote-server_1  | Error: Access denied for user 'root'@'172.29.0.3' (using password: YES)
eoapi-remote-server_1  |     at Packet.asError (/eoapi-remote-server/node_modules/mysql2/lib/packets/packet.js:728:17)
eoapi-remote-server_1  |     at ClientHandshake.execute (/eoapi-remote-server/node_modules/mysql2/lib/commands/command.js:29:26)
eoapi-remote-server_1  |     at PoolConnection.handlePacket (/eoapi-remote-server/node_modules/mysql2/lib/connection.js:456:32)
eoapi-remote-server_1  |     at PacketParser.onPacket (/eoapi-remote-server/node_modules/mysql2/lib/connection.js:85:12)
eoapi-remote-server_1  |     at PacketParser.executeStart (/eoapi-remote-server/node_modules/mysql2/lib/packet_parser.js:75:16)
eoapi-remote-server_1  |     at Socket.<anonymous> (/eoapi-remote-server/node_modules/mysql2/lib/connection.js:92:25)
eoapi-remote-server_1  |     at Socket.emit (node:events:527:28)
eoapi-remote-server_1  |     at addChunk (node:internal/streams/readable:315:12)
eoapi-remote-server_1  |     at readableAddChunk (node:internal/streams/readable:289:9)
eoapi-remote-server_1  |     at Socket.Readable.push (node:internal/streams/readable:228:10)
eoapi-remote-server_1  | [Nest] 27  - 07/23/2022, 10:14:54 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
eoapi-remote-server_1  | Error: Access denied for user 'root'@'172.29.0.3' (using password: YES)
eoapi-remote-server_1  |     at Packet.asError (/eoapi-remote-server/node_modules/mysql2/lib/packets/packet.js:728:17)
eoapi-remote-server_1  |     at ClientHandshake.execute (/eoapi-remote-server/node_modules/mysql2/lib/commands/command.js:29:26)
eoapi-remote-server_1  |     at PoolConnection.handlePacket (/eoapi-remote-server/node_modules/mysql2/lib/connection.js:456:32)
eoapi-remote-server_1  |     at PacketParser.onPacket (/eoapi-remote-server/node_modules/mysql2/lib/connection.js:85:12)
eoapi-remote-server_1  |     at PacketParser.executeStart (/eoapi-remote-server/node_modules/mysql2/lib/packet_parser.js:75:16)
eoapi-remote-server_1  |     at Socket.<anonymous> (/eoapi-remote-server/node_modules/mysql2/lib/connection.js:92:25)
eoapi-remote-server_1  |     at Socket.emit (node:events:527:28)
eoapi-remote-server_1  |     at addChunk (node:internal/streams/readable:315:12)
eoapi-remote-server_1  |     at readableAddChunk (node:internal/streams/readable:289:9)
eoapi-remote-server_1  |     at Socket.Readable.push (node:internal/streams/readable:228:10)
^CERROR: Aborting.
```

**Comment by buqiyuan** [comment]
<img width="692" alt="image" src="https://user-images.githubusercontent.com/39730999/180609322-289c4c12-a9eb-422a-b752-d6c10fbc96d9.png">
你进入mysql容器，使用你设置的密码看能登录吗？如果你改过`config.production.ts`文件，则需要删除它之前的镜像，重新构建

**Comment by scarqin** [comment]
> 你这里连接不上数据库，主要应该是密码不对，看下这两个地方密码一样吗？ <img alt="image" width="1619" src="https://user-images.githubusercontent.com/39730999/180608677-8cde85c8-4bb6-4c7a-aadc-cfcd7c3f8fda.png">

@buqiyuan 同样的数据库配置要在两个地方维护吗，统一会更好？

**Comment by buqiyuan** [comment]
> > 你这里连接不上数据库，主要应该是密码不对，看下这两个地方密码一样吗？ <img alt="image" width="1619" src="https://user-images.githubusercontent.com/39730999/180608677-8cde85c8-4bb6-4c7a-aadc-cfcd7c3f8fda.png">
> 
> @buqiyuan 同样的数据库配置要在两个地方维护吗，统一会更好？

可以，那就统一使用环境变量文件？然后每次修改为不同密码之后，mysql服务的root下的密码也要实时更改吗？

**Comment by axty666** [comment]
> 

确实是能登录进去的 删除掉容器和images后确实成功链接到数据库了 直接访问返回`Eoapi,Hello World!`
但是客户端连接显示`远程服务器连接失败`

**Comment by scarqin** [comment]
你配置的地址和 token 对吗？
![](https://user-images.githubusercontent.com/15225835/180610590-bada0be0-2a2c-4a2b-b3c3-62110376134e.png)

**Comment by axty666** [comment]
> 

域名和解析到的ip都试了 token没有改过

**Comment by scarqin** [comment]
有这个文件吧？
![](https://user-images.githubusercontent.com/15225835/180610954-bc0bce07-7f13-478f-98de-10e4ec47cfdf.png)

**Comment by axty666** [comment]
> 有这个文件吧？ ![](https://user-images.githubusercontent.com/15225835/180610954-bc0bce07-7f13-478f-98de-10e4ec47cfdf.png)

![image](https://user-images.githubusercontent.com/76648930/180611216-1d29807f-130f-492f-846f-9b2b06f9d1cf.png)

**Comment by buqiyuan** [comment]
> ![image](https://user-images.githubusercontent.com/76648930/180611216-1d29807f-130f-492f-846f-9b2b06f9d1cf.png)
`.env`是在构建镜像之前就创建的了吗？还是刚刚才创建的，如果是刚创建的，则需要删除旧镜像，重新构建

**Comment by scarqin** [comment]
可以通过 system/status 接口看看服务鉴权能否通过
![](https://user-images.githubusercontent.com/15225835/180611472-253a7a04-4e64-4cc1-8362-190368ee8316.png)

**Comment by axty666** [comment]
ok 终于是成功连接到了 万分感谢
